const Map<String, String> enUS = {
  "AuthTitle": "Login to your account",
  "flyaway": "flyaway",
  "authEmail": "Email",
  "authPhone" : "Phone",
  "authName": "Name",
  'otpSuccess' : 'Otp has sent successfully!',
  'fillOtpCode' : 'Enter the code sent to your phone number',
  'verifyPhone' : 'Verify Phone Number',
  'enterOtpSentTo' : 'Enter OTP sent to :',
  "authLastName": "Last name",
  "authButton": 'Send OTP',
  "didntReceiveCode" : 'Didn\'t receive code?',
  "resendOtpIn" : 'Resend OTP in',
  "resendOtp" : 'Resend OTP',
  "verify" : 'Verify',
  "authSnackBarErrorWarn": "Warning !",
  "authSnackBarError": "please fill all required fields",
  "authSuccessLogin": 'Success',
  "authSuccessLoginTextMsg": "Welcome To Application",
  "bottomSheetChangeLang": "change Language",
  "select_preferred_language": "choose your preferred language ",
  "change_theme": "Change Theme",
  "current_language": "Current Language",
  "change_language": "Change Language",
  "view_available_tickets": "View Available Tickets",
  "get_taxi" : 'Request Service',
  "Explore_global_destinations": 'Explore Global Destinations with fly away!',
  "search_box": "Search",
  "bottom_nav_home": "Home",
  "bottom_nav_search": "Search",
  "bottom_nav_trips": "My trips",
  "bottom_nav_profile": "Profile",
  "categories_text": "Categories",
  "hotel": "Hotel",
  "airplane": "Airplane",
  "train": "Train",
  "bus": "Bus",
  "taxi": "Taxi",
  "confirmed": 'Confirmed',
  "plane": "Airplane",
  "Standard": "Standard",
  "Business": "Business",
  "FirstClass": "First Class",
  "Economy": "Economy",
  "Premium": "Premium",
  "Basic": "Basic",
  "Domestic": "Domestic",
  "International": "International",
  "Departure": "Departure",
  "Arrival": "Arrival",
  "Flight": "Flight",
  "Total Price": "Total Price",
  "select_your_seat": "Select Your Seat",
  'select_your_ticket_info': 'Select Your Ticket Info',
  'origin': 'origin',
  'destination': 'destination',
  'travelTime': 'Travel Time',
  'passengers': 'passengers',
  'originDesc' : 'Enter origin city',
  'destinationDesc' : 'Enter destination city',
  'travelTimeDesc' : 'Select travel time',
  'passengersDesc' : 'Number of passengers',
  'buyTicket' : 'Buy Ticket',
  'fillAllFieldsToSeePrice' : 'Please fill all fields to see price',
  'discover_new_adventures' : 'Discover New Adventures',
  'plan_your_next_journey' : 'Plan Your Next Journey',
  'travel_the_world_with_us' : 'Travel The World With Us',
  'taxi_internet_with_us' : 'Taxi Internet is always available for you!',
  'fullName' : 'Full Name',
  'emailAddress' : 'Email Address',
  'phoneNumber' : 'Phone Number',
  'editProfile' : 'Edit Profile',
  'personalInformation' : 'Personal Information',
  'notSet' : 'Not Set',
  'saveChanges' : 'Save Changes',
  'cancel' : 'Cancel',
  'enterEmail' : 'Enter Email',
  'enterPhoneNumber' : 'Enter Phone Number',
  'edit' : 'Edit',
  'exitToApp' : 'log out from my account',
};
