const Map<String, String> enUS = {
  "AuthTitle": "Login to your account",
  "flyaway": "flyaway",
  "authEmail": "Email",
  "authName": "Name",
  "authLastName": "Last name",
  "authButton": 'Login To App',
  "authSnackBarErrorWarn": "Warning !",
  "authSnackBarError": "please fill all required fields",
  "authSuccessLogin": 'Success',
  "authSuccessLoginTextMsg": "Welcome To Application",
  "bottomSheetChangeLang": "change Language",
  "select_preferred_language": "choose your preferred language ",
  "change_theme": "Change Theme",
  "current_language": "Current Language",
  "change_language": "Change Language",
  "view_available_tickets": "View Available Tickets",
  "Explore_global_destinations": 'Explore Global Destinations with fly away!',
  "search_box": "Search",
  "bottom_nav_home": "Home",
  "bottom_nav_search": "Search",
  "bottom_nav_trips": "My trips",
  "bottom_nav_profile": "Profile",
  "categories_text": "Categories",
  "hotel": "Hotel",
  "airplane": "Airplane",
  "train": "Train",
  "bus": "Bus",
  "taxi": "Taxi",
  "confirmed": 'Confirmed',
  "plane": "Airplane",
  "Standard": "Standard",
  "Business": "Business",
  "FirstClass": "First Class",
  "Economy": "Economy",
  "Premium": "Premium",
  "Basic": "Basic",
  "Domestic": "Domestic",
  "International": "International",
  "Departure": "Departure",
  "Arrival": "Arrival",
  "Flight": "Flight",
  "Total Price": "Total Price",
  "select_your_seat": "Select Your Seat",
  'select_your_ticket_info': 'Select Your Ticket Info',
  'origin': 'origin',
  'destination': 'destination',
  'travelTime': 'Travel Time',
  'passengers': 'passengers',
  'originDesc' : 'Enter origin city',
  'destinationDesc' : 'Enter destination city',
  'travelTimeDesc' : 'Select travel time',
  'passengersDesc' : 'Number of passengers',
  'buyTicket' : 'Buy Ticket',
  'fillAllFieldsToSeePrice' : 'Please fill all fields to see price'
};
