const Map<String, String> faIR = {
  "AuthTitle": "وارد حساب کاربری خود شوید",
  "flyaway": "فلای اوی",
  "authEmail": "ایمیل",
  "authPhone" : "شماره همراه",
  "authName": "نام",
  "authLastName": "نام خانوادگی",
  "authButton": "ارسال کد تایید",
  "authSnackBarErrorWarn": "خطا",
  'otpSuccess' : 'کد ورود با موفقیت ارسال شد !',
  'fillOtpCode' : 'کد ارسال شده به شماره خود را وارد کنید',
  'verifyPhone' : 'احراز هویت شماره تلفن',
  'enterOtpSentTo' : 'شماره ارسال شده به :',
  'didntReceiveCode' : 'کد را دریافت نکرده اید؟',
  'resendOtpIn' : 'امکان درخواست کد مجدد :',
  'resendOtp' : 'ارسال دوباره کد',
  'verify' : 'ورود به اپلیکیشن',
  "authSnackBarError": 'لطفا تمامی فیلد های لازم رو کامل کنید',
  "authSuccessLogin": "موفقیت آمیز !",
  "authSuccessLoginTextMsg": "به اپلیکیشن خوش آمدید !",
  "bottomSheetChangeLang": "تغییر زبان",
  "select_preferred_language": "زبان مد نظر خود را انتخاب کنید",
  "change_theme": "تغییر تم",
  "current_language": "زبان فعلی",
  "change_language": "تغییر زبان",
  "view_available_tickets": "مشاهده بلیط ها",
  "get_taxi" : 'درخواست خودرو',
  "Explore_global_destinations": 'با فلای اوی , راحت همه جا برو',
  "search_box": "جستجو",
  "bottom_nav_home": "خانه",
  "bottom_nav_search": "جستجو",
  "bottom_nav_trips": "سفر های من",
  "bottom_nav_profile": "پروفایل",
  "categories_text": "دسته بندی ها",
  "hotel": "هتل",
  "airplane": 'هواپیما',
  "train": "قطار",
  "bus": "اتوبوس",
  "taxi": "تاکسی",
  "confirmed": 'تایید شده',
  "plain": 'هواپیما',
  "Standard": "استاندارد",
  "Business": "بیزینس",
  "FirstClass": "درجه یک",
  "Economy": "اکونومی",
  "Premium": "پریمیوم",
  "Basic": "پایه",
  "Domestic": "داخلی",
  "International": "بین المللی",
  "Departure": "حرکت",
  "Arrival": "ورود",
  "Flight": "پرواز",
  "Total Price": "قیمت کل",
  "select_your_seat" : "صندلی خود را انتخاب کنید",
  "select_your_ticket_info" : 'بلیط خود را انتخاب کنید',
  'origin': 'مبدا',
  'destination': 'مقصد',
  'travelTime': 'زمان بلیط',
  'passengers': ' مسافران',
  'originDesc' : 'شهر مبدا را وارد کنید',
  'destinationDesc' : 'شهر مقصد را وارد کنید',
  'travelTimeDesc' : 'زمان بلیط را انتخاب کنید',
  'passengersDesc' : 'تعداد مسافران',
  'buyTicket' : 'خرید بلیط',
  'fillAllFieldsToSeePrice' : 'لطفا تمام فیلد های لازم رو پر کنید',
  'discover_new_adventures' : 'هر سفر , ی ماجرای جدید',
  'plan_your_next_journey' : 'فلای اوی , عامل آرامش تو',
  'travel_the_world_with_us' : 'با فلاوی اوی هرجا دلت خواست برو',
  'taxi_internet_with_us' : 'تاکسی اینترنتی همیشه در خدمت شماست!',
  'fullName' : 'نام و نام خانوادگی',
  'emailAddress' : 'آدرس ایمیل',
  'phoneNumber' : 'شماره تلفن',
  'editProfile' : 'ویرایش پروفایل',
  'personalInformation' : 'اطلاعات شخصی',
  'notSet' : 'وارد نشده',
  'saveChanges' : 'ذخیره تغییرات',
  'cancel' : 'لغو',
  'enterEmail' : 'ایمیل خود را وارد کنید',
  'enterPhoneNumber' : 'شماره تلفن خود را وارد کنید',
  'edit' : 'ویرایش',
  'exitToApp' : 'خروج از حساب کاربری',
  'walletCount' : 'کیف پول',
  'paymentsMethod' : 'روش های پرداخت',
  'yourBalance' : 'موجودی فعلی :',
  'addCount' : 'افزایش موجودی',
  'countField' : 'مبلغ مورد نظر',
  'amountPaid' : 'مبلغ پرداخت شده',
  'ticketId' : 'شماره بلیط'
};