const Map<String, String> faIR = {
  "AuthTitle": "وارد حساب کاربری خود شوید",
  "flyaway": "فلای اوی",
  "authEmail": "ایمیل",
  "authName": "نام",
  "authLastName": "نام خانوادگی",
  "authButton": "ورود به اپلیکیشن",
  "authSnackBarErrorWarn": "خطا",
  "authSnackBarError": 'لطفا تمامی فیلد های لازم رو کامل کنید',
  "authSuccessLogin": "موفقیت آمیز !",
  "authSuccessLoginTextMsg": "به اپلیکیشن خوش آمدید !",
  "bottomSheetChangeLang": "تغییر زبان",
  "select_preferred_language": "زبان مد نظر خود را انتخاب کنید",
  "change_theme": "تغییر تم",
  "current_language": "زبان فعلی",
  "change_language": "تغییر زبان",
  "view_available_tickets": "مشاهده بلیط ها",
  "Explore_global_destinations": 'با فلای اوی , راحت همه جا برو',
  "search_box": "جستجو",
  "bottom_nav_home": "خانه",
  "bottom_nav_search": "جستجو",
  "bottom_nav_trips": "سفر های من",
  "bottom_nav_profile": "پروفایل",
  "categories_text": "دسته بندی ها",
  "hotel": "هتل",
  "airplane": 'هواپیما',
  "train": "قطار",
  "bus": "اتوبوس",
  "taxi": "تاکسی",
  "confirmed": 'تایید شده',
  "plain": 'هواپیما',
  "Standard": "استاندارد",
  "Business": "بیزینس",
  "FirstClass": "درجه یک",
  "Economy": "اکونومی",
  "Premium": "پریمیوم",
  "Basic": "پایه",
  "Domestic": "داخلی",
  "International": "بین المللی",
  "Departure": "حرکت",
  "Arrival": "ورود",
  "Flight": "پرواز",
  "Total Price": "قیمت کل",
  "select_your_seat" : "صندلی خود را انتخاب کنید",
  "select_your_ticket_info" : 'بلیط خود را انتخاب کنید',
  'origin': 'مبدا',
  'destination': 'مقصد',
  'travelTime': 'زمان بلیط',
  'passengers': ' مسافران',
  'originDesc' : 'شهر مبدا را وارد کنید',
  'destinationDesc' : 'شهر مقصد را وارد کنید',
  'travelTimeDesc' : 'زمان بلیط را انتخاب کنید',
  'passengersDesc' : 'تعداد مسافران',
  'buyTicket' : 'خرید بلیط',
  'fillAllFieldsToSeePrice' : 'لطفا تمام فیلد های لازم رو پر کنید'
};